version: '2'

volumes:
  data:

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.14
    container_name: mosquitto
    restart: always
    environment:
      - TZ=Europe/Moscow
      - PUID=1001
      - PGID=33
    volumes:
      - data:/mosquitto/data
      - ./config:/mosquitto/config
    ports:
      - '1883:1883'

