version: '2'

networks:
  traefik:
    external: true

volumes:
  data:

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.14
    container_name: mosquitto
    restart: always
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
    volumes:
      - data:/mosquitto/data
      - ./config:/mosquitto/config
    ports:
      - '1883:1883'
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mosquitto-secure.rule=HostSNI(`$DOMAIN`)"
      - "traefik.tcp.routers.mosquitto-secure.tls.certresolver=default"
      - "traefik.tcp.routers.mosquitto-secure.service=mosquitto"
      - "traefik.tcp.services.mosquitto.loadbalancer.server.port=1883"

  keepalived:
    # osixia/keepalived doen't support ARM currently, so build it localy
    #image: osixia/keepalived:2.0.20
    build: ./keepalived
    restart: always
    network_mode: host
    command: ["--copy-service"]
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    environment:
      - "MQTT_HOST=${MQTT_HOST}"
      - "MQTT_USER=${MQTT_USER}"
      - "MQTT_PASSWORD=${MQTT_PASSWORD}"

